name: Hit Counter

on:
  push:
    branches:
      - main
  workflow_dispatch:
  page_build:
    types:
      - built

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Update hit counter
        run: |
          python update_counter.py

      - name: Commit and push changes
        # uses: crazy-max/ghaction-github-pages@v3.1.0
        # with:
        #   target_branch: main
        #   build_dir: profile-3d-contrib
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        run: |
          git config --global --add safe.directory /home/runner/work/github-profile-hit-counter/profile-hit-counter
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update hit counter'
          git push
